server:
  port: 9010

spring:
  application:
    name: tubin

turbine:
  aggregator:
    clusterConfig: default
  appConfig: youkong-ui
  clusterNameExpression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/
