server:
  port: 9002

spring:
  application:
    name: youkong-ui
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html   
    
  #sleuth:
    #web:
      #client:
        #enabled: true
    #sampler:
      #probability: 1.0
  #zipkin:
     #baseUrl: http://localhost:9003
     #sender:
        #type: rabbit
        
      
        
eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/



feign:
  hystrix:
    enabled: true



     